export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG'
export const CHANGE_PALY_LIST = 'player/CHANGE_PALY_LIST'
export const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX'

export const CHANGE_SEQUENCE = 'player/CHANGE_SEQUENCE'
